# Generated by Django 4.2.2 on 2023-06-21 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default=datetime.date(2023, 6, 21)),
        ),
    ]
